version: '3'

# Containers to be instantiated in environment
services:
  jupyter:
    image: workshop-docker/example4
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/tmp/notebooks
    links:
      - <mysql-container-service-name>
  mysql:
    image: mysql/mysql-server
    volumes:
      - <data-volume>:<mount-point>

# External volumes for the declared services
volumes:
  workshop-docker-mysqldata:
    external:
      name: workshop-docker-mysqldata
